# **NumPy**

## Topics

1. What is NumPy
2. Create NumPy array
3. 1D and 2D arrays
4. Indexing
5. Slicing
6. Mathematical operations
7. Aggregate functions

8. `shape`, `ndim`, `size`
9. data types with `dtype` and type conversion
10. `zeros()`, `ones()`, `arange()`, `linspace()`
11. reshaping with `reshape()`
12. flattening with `flatten()` / `ravel()`
13. boolean masking
14. conditional filtering
15. broadcasting
16. axis concept
17. statistical functions: `mean()`, `median()`, `std()`, `var()`
18. `min()`, `max()`, `sum()`, `cumsum()`
19. sorting with `sort()`
20. copying vs viewing
21. random module
22. stacking arrays
23. splitting arrays
24. universal functions (`sqrt`, `log`, `exp`, etc.)
25. handling missing values basics (`nan`)
26. basic linear algebra functions
27. practical NumPy for data analytics workflow


In [1]:
# NumPy introduction

# NumPy is used for fast numerical calculations
# NumPy array is similar to a Python list, but more powerful

import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("NumPy Array:")
print(arr)

print("\nType of arr:")
print(type(arr))

NumPy Array:
[10 20 30 40 50]

Type of arr:
<class 'numpy.ndarray'>


In [2]:
# 1D and 2D arrays

# 1D array = one row of values
# 2D array = rows and columns like table

import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array (Row then Column)
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("1D Array:")
print(arr1)

print("\n2D Array:")
print(arr2)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
# Shape and dimension

# shape tells rows and columns
# ndim tells dimension

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Shape of arr1:", arr1.shape)
print("Dimension of arr1:", arr1.ndim)

print("Shape of arr2:", arr2.shape)
print("Dimension of arr2:", arr2.ndim)

Shape of arr1: (4,)
Dimension of arr1: 1
Shape of arr2: (2, 3)
Dimension of arr2: 2


In [4]:
# Indexing in NumPy

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Full array:")
print(arr)

print("\nFirst element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

Full array:
[10 20 30 40 50]

First element: 10
Third element: 30
Last element: 50


In [5]:
# Slicing in NumPy

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print("Original array:")
print(arr)

print("\nElements from index 1 to 4:")
print(arr[1:5])

print("\nFirst 3 elements:")
print(arr[:3])

print("\nLast 2 elements:")
print(arr[-2:])

Original array:
[10 20 30 40 50 60]

Elements from index 1 to 4:
[20 30 40 50]

First 3 elements:
[10 20 30]

Last 2 elements:
[50 60]


In [6]:
# 2D array indexing

# first value is row index
# second value is column index

import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("2D Array:")
print(arr)

print("\nElement at row 0, column 1:", arr[0, 1])
print("Element at row 1, column 2:", arr[1, 2])

2D Array:
[[10 20 30]
 [40 50 60]]

Element at row 0, column 1: 20
Element at row 1, column 2: 60


In [9]:
# Mathematical operations

# NumPy can do element-wise operations very easily

import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print("Array 1:", arr1)
print("Array 2:", arr2)

print("\nAddition:")
print(arr1 + arr2)

print("\nSubtraction:")
print(arr1 - arr2)

print("\nMultiplication:")
print(arr1 * arr2)

print("\nDivision:")
print(arr1 / arr2)

Array 1: [10 20 30]
Array 2: [1 2 3]

Addition:
[11 22 33]

Subtraction:
[ 9 18 27]

Multiplication:
[10 40 90]

Division:
[10. 10. 10.]


In [10]:
# Useful NumPy functions

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)

print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Array: [10 20 30 40 50]

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [11]:
# Special arrays

import numpy as np

# Array of zeros
a = np.zeros(5)

# Array of ones
b = np.ones(5)

# Range of values
c = np.arange(1, 11)

print("Zeros array:")
print(a)

print("\nOnes array:")
print(b)

print("\nRange array:")
print(c)

Zeros array:
[0. 0. 0. 0. 0.]

Ones array:
[1. 1. 1. 1. 1.]

Range array:
[ 1  2  3  4  5  6  7  8  9 10]


### Pandas = table data
### NumPy = fast numeric array operations
### NumPy helps a lot in analytics, statistics, and machine learning

In [12]:
# shape, ndim, size

import numpy as np

# Create a 2D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Array:")
print(arr)

# shape = number of rows and columns
print("\nShape:", arr.shape)

# ndim = number of dimensions
print("Number of dimensions:", arr.ndim)

# size = total number of elements
print("Total number of elements:", arr.size)

Array:
[[10 20 30]
 [40 50 60]]

Shape: (2, 3)
Number of dimensions: 2
Total number of elements: 6


In [13]:
# Data Types with dtype and type conversion

import numpy as np

# Create array of integers
arr = np.array([1, 2, 3, 4, 5])

print("Original array:")
print(arr)

# Check data type
print("\nData type:", arr.dtype)

# Convert integer array to float array
arr_float = arr.astype(float)

print("\nConverted to float:")
print(arr_float)
print("New data type:", arr_float.dtype)

Original array:
[1 2 3 4 5]

Data type: int64

Converted to float:
[1. 2. 3. 4. 5.]
New data type: float64


In [14]:
# zeros(), ones(), arange(), linspace()

import numpy as np

# Array of zeros
a = np.zeros(5)
print("zeros():")
print(a)

# Array of ones
b = np.ones(5)
print("\nones():")
print(b)

# Range of values
c = np.arange(1, 11)
print("\narange():")
print(c)

# Evenly spaced values
d = np.linspace(0, 10, 5)
print("\nlinspace():")
print(d)

zeros():
[0. 0. 0. 0. 0.]

ones():
[1. 1. 1. 1. 1.]

arange():
[ 1  2  3  4  5  6  7  8  9 10]

linspace():
[ 0.   2.5  5.   7.5 10. ]


In [15]:
# reshaping with reshape()

import numpy as np

# Create 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

print("Original array:")
print(arr)

# Reshape into 2 rows and 3 columns
reshaped = arr.reshape(2, 3)

print("\nReshaped array (2 x 3):")
print(reshaped)

Original array:
[1 2 3 4 5 6]

Reshaped array (2 x 3):
[[1 2 3]
 [4 5 6]]


In [16]:
# flattening with flatten() / ravel()

import numpy as np

# Create 2D array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original 2D array:")
print(arr)

# Convert into 1D array using flatten()
flat1 = arr.flatten()
print("\nFlatten using flatten():")
print(flat1)

# Convert into 1D array using ravel()
flat2 = arr.ravel()
print("\nFlatten using ravel():")
print(flat2)

Original 2D array:
[[1 2 3]
 [4 5 6]]

Flatten using flatten():
[1 2 3 4 5 6]

Flatten using ravel():
[1 2 3 4 5 6]


In [17]:
# boolean masking

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original array:")
print(arr)

# Create boolean mask
mask = arr > 25

print("\nBoolean mask (arr > 25):")
print(mask)

# Use mask to get values
print("\nValues greater than 25:")
print(arr[mask])

Original array:
[10 20 30 40 50]

Boolean mask (arr > 25):
[False False  True  True  True]

Values greater than 25:
[30 40 50]


In [18]:
# conditional filtering

import numpy as np

arr = np.array([5, 12, 18, 25, 30, 7])

print("Original array:")
print(arr)

# Filter values greater than 15
filtered = arr[arr > 15]

print("\nFiltered values greater than 15:")
print(filtered)

Original array:
[ 5 12 18 25 30  7]

Filtered values greater than 15:
[18 25 30]


In [19]:
# broadcasting


import numpy as np

arr = np.array([10, 20, 30, 40])

print("Original array:")
print(arr)

# Add one number to all elements
result = arr + 5

print("\nAfter adding 5 to all elements:")
print(result)

# Multiply all elements by 2
result2 = arr * 2

print("\nAfter multiplying by 2:")
print(result2)


Original array:
[10 20 30 40]

After adding 5 to all elements:
[15 25 35 45]

After multiplying by 2:
[20 40 60 80]


In [20]:
# axis concept

import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Array:")
print(arr)

# Sum column-wise
print("\nSum with axis=0 (column-wise):")
print(np.sum(arr, axis=0))

# Sum row-wise
print("\nSum with axis=1 (row-wise):")
print(np.sum(arr, axis=1))

Array:
[[10 20 30]
 [40 50 60]]

Sum with axis=0 (column-wise):
[50 70 90]

Sum with axis=1 (row-wise):
[ 60 150]


In [21]:
# statistical functions: mean(), median(), std(), var()

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:")
print(arr)

print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Array:
[10 20 30 40 50]

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0


In [22]:
# min(), max(), sum(), cumsum()


import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:")
print(arr)

print("\nMinimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Sum:", np.sum(arr))
print("Cumulative Sum:", np.cumsum(arr))

Array:
[10 20 30 40 50]

Minimum: 10
Maximum: 50
Sum: 150
Cumulative Sum: [ 10  30  60 100 150]


In [23]:
# sorting with sort()

import numpy as np

arr = np.array([40, 10, 30, 20, 50])

print("Original array:")
print(arr)

# Sort array
sorted_arr = np.sort(arr)

print("\nSorted array:")
print(sorted_arr)

Original array:
[40 10 30 20 50]

Sorted array:
[10 20 30 40 50]


In [24]:
# copying vs viewing

import numpy as np

arr = np.array([10, 20, 30, 40])

print("Original array:")
print(arr)

# View shares memory
view_arr = arr.view()

# Copy creates separate memory
copy_arr = arr.copy()

# Change original array
arr[0] = 999

print("\nAfter changing original array:")
print("Original array:", arr)
print("View array:", view_arr)
print("Copy array:", copy_arr)

Original array:
[10 20 30 40]

After changing original array:
Original array: [999  20  30  40]
View array: [999  20  30  40]
Copy array: [10 20 30 40]


In [25]:
# random module

import numpy as np

# Random integer values
rand_int = np.random.randint(1, 10, size=5)
print("Random integers:")
print(rand_int)

# Random float values between 0 and 1
rand_float = np.random.rand(5)
print("\nRandom floats:")
print(rand_float)

# Random 2D array
rand_2d = np.random.randint(1, 100, size=(2, 3))
print("\nRandom 2D array:")
print(rand_2d)

Random integers:
[6 2 3 1 2]

Random floats:
[0.74441608 0.99405618 0.39281248 0.38539869 0.9706127 ]

Random 2D array:
[[89 68 88]
 [46 83 80]]


In [26]:
# stacking arrays

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Array a:")
print(a)

print("\nArray b:")
print(b)

# Horizontal stacking
h_stack = np.hstack((a, b))
print("\nHorizontal stack:")
print(h_stack)

# Vertical stacking
v_stack = np.vstack((a, b))
print("\nVertical stack:")
print(v_stack)

Array a:
[1 2 3]

Array b:
[4 5 6]

Horizontal stack:
[1 2 3 4 5 6]

Vertical stack:
[[1 2 3]
 [4 5 6]]


In [27]:
# splitting arrays

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print("Original array:")
print(arr)

# Split into 3 equal parts
split_arr = np.split(arr, 3)

print("\nSplit array into 3 parts:")
print(split_arr)

Original array:
[10 20 30 40 50 60]

Split array into 3 parts:
[array([10, 20]), array([30, 40]), array([50, 60])]


In [28]:
# universal functions (sqrt, log, exp, etc.)


import numpy as np

arr = np.array([1, 4, 9, 16])

print("Array:")
print(arr)

print("\nSquare root:")
print(np.sqrt(arr))

print("\nExponential:")
print(np.exp(arr))

print("\nLogarithm:")
print(np.log(arr))

Array:
[ 1  4  9 16]

Square root:
[1. 2. 3. 4.]

Exponential:
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]

Logarithm:
[0.         1.38629436 2.19722458 2.77258872]


In [29]:
# handling missing values basics (nan)

import numpy as np

arr = np.array([10, 20, np.nan, 40, 50])

print("Array with missing value:")
print(arr)

# Check missing values
print("\nIs NaN present?")
print(np.isnan(arr))

# Mean ignoring NaN
print("\nMean ignoring NaN:")
print(np.nanmean(arr))

# Sum ignoring NaN
print("\nSum ignoring NaN:")
print(np.nansum(arr))

Array with missing value:
[10. 20. nan 40. 50.]

Is NaN present?
[False False  True False False]

Mean ignoring NaN:
30.0

Sum ignoring NaN:
120.0


In [30]:
# basic linear algebra functions

import numpy as np

a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:")
print(a)

print("\nMatrix B:")
print(b)

# Matrix multiplication
print("\nMatrix multiplication:")
print(np.dot(a, b))

# Transpose
print("\nTranspose of A:")
print(a.T)

# Determinant
print("\nDeterminant of A:")
print(np.linalg.det(a))

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix multiplication:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004


In [31]:
# practical NumPy for data analytics workflow

import numpy as np

# Sales data of 7 days
sales = np.array([200, 250, 180, 300, 280, 220, 260])

print("Sales data:")
print(sales)

# Basic analysis
print("\nTotal sales:", np.sum(sales))
print("Average sales:", np.mean(sales))
print("Maximum sales:", np.max(sales))
print("Minimum sales:", np.min(sales))

# Days where sales are greater than 240
print("\nSales greater than 240:")
print(sales[sales > 240])

# Add bonus 20 to all days
updated_sales = sales + 20
print("\nUpdated sales after bonus:")
print(updated_sales)

# Sort sales
print("\nSorted sales:")
print(np.sort(sales))

Sales data:
[200 250 180 300 280 220 260]

Total sales: 1690
Average sales: 241.42857142857142
Maximum sales: 300
Minimum sales: 180

Sales greater than 240:
[250 300 280 260]

Updated sales after bonus:
[220 270 200 320 300 240 280]

Sorted sales:
[180 200 220 250 260 280 300]


numpy completed